apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: dunkzilla10/post:latest
        ports:
        - containerPort: 6054
        - containerPort: 6054
      nodeSelector:
        kubernetes.io/hostname: labfinal